## Handling Nominal categorical data:

`Nominal categorical data` is a type of qualitative data that uses labels and tags to classify data into groups without any numerical values.

<img src="images/nominal.png" alt="Image Description" width="550" height="250">

## One Hot Encoding:

`One-hot encoding` is a technique used to convert categorical data into a binary format where each category is represented by a separate column with a 1 indicating its presence and 0s for all other categories.

<img src="images/ohe.png" alt="Image Description" width="550" height="230">

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Datasets/data_for_ohe.csv')

In [3]:
df.head()

gender race/ethnicity         lunch  math score  reading score
0  female        group B      standard          72             72
1  female        group C      standard          69             90
2  female        group B      standard          90             95
3    male        group A  free/reduced          47             57
4    male        group C      standard          76             78

In [8]:
print(df['gender'].unique())
print(df['race/ethnicity'].unique())
print(df['lunch'].unique())

['female' 'male']
['group B' 'group C' 'group A' 'group D' 'group E']
['standard' 'free/reduced']


So, get_dummies function will create 9 new columns and deletes the existing columns.

## 1. One Hot Encoding Using Pandas:

- Using `get_dummies` function:

In [9]:
temp = pd.get_dummies(df,columns=['gender','race/ethnicity','lunch'],dtype=np.int32)

In [10]:
temp.sample(4)

math score  reading score  gender_female  gender_male  \
924          74             70              0            1   
109          70             64              1            0   
333          90             78              0            1   
133          75             81              1            0   

     race/ethnicity_group A  race/ethnicity_group B  race/ethnicity_group C  \
924                       0                       0                       0   
109                       0                       1                       0   
333                       0                       1                       0   
133                       0                       0                       1   

     race/ethnicity_group D  race/ethnicity_group E  lunch_free/reduced  \
924                       1                       0                   1   
109                       0                       0                   0   
333                       0                       0                   0   
133                       0                       0                   0   

     lunch_standard  
924               0  
109               1  
333               1  
133               1

In [12]:
temp.shape

(1000, 11)

### `drop_first = True`

- This parameter drops first column of each dummy column i.e `three`.    
- It is used to eliminate multicollinearity from the data.. -> Each column used be independent to each other.

- `Multicollinearity` in machine learning (ML) is a situation where two or more independent variables in a regression model are highly correlated. This can negatively impact the model's performance and the accuracy of its predictions. 

In [13]:
new_temp = pd.get_dummies(df,columns=['gender','race/ethnicity','lunch'],dtype=np.int32,drop_first=True)

In [14]:
new_temp.sample(4)

math score  reading score  gender_male  race/ethnicity_group B  \
748          50             60            0                       0   
226          72             72            0                       0   
679          63             61            1                       0   
527          36             53            0                       0   

     race/ethnicity_group C  race/ethnicity_group D  race/ethnicity_group E  \
748                       1                       0                       0   
226                       1                       0                       0   
679                       0                       1                       0   
527                       1                       0                       0   

     lunch_standard  
748               0  
226               1  
679               0  
527               0

In [15]:
new_temp.shape

(1000, 8)

## One Hot Encoding Using Sklearn:

1. train test split:

In [16]:
df.head(2)

gender race/ethnicity     lunch  math score  reading score
0  female        group B  standard          72             72
1  female        group C  standard          69             90

In [17]:
from sklearn.model_selection import train_test_split

x = df.iloc[:,0:4]
y = df.iloc[:,-1]
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [19]:
X_train.sample(4)

gender race/ethnicity         lunch  math score
458  female        group E      standard         100
768  female        group D      standard          68
517  female        group E      standard          66
466  female        group D  free/reduced          26

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe = OneHotEncoder()

In [24]:
ohe.fit(X_train[['gender','race/ethnicity','lunch']])

OneHotEncoder()

In [29]:
new_X_train = ohe.transform(X_train[['gender','race/ethnicity','lunch']])
new_X_test = ohe.transform(X_test[['gender','race/ethnicity','lunch']])

In [27]:
new_X_train # It will return spare matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2400 stored elements and shape (800, 9)>

In [ ]:
new_X_test.toarray() # toarray() can be should to convert the data to a numpy array

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.]])

- `sparse_output=False` and `dtype=np.int32`

Instead to using toarray() we can use the parameter sparse_output = False..    
Using dtype parameter we can change the type from float to int..

In [33]:
ohe = OneHotEncoder(sparse_output=False,dtype=np.int32)

ohe.fit(X_train[['gender','race/ethnicity','lunch']])
new_X_train = ohe.transform(X_train[['gender','race/ethnicity','lunch']])
new_X_test = ohe.transform(X_test[['gender','race/ethnicity','lunch']])

new_X_train

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 0, 1]], dtype=int32)

In [34]:
new_X_train.shape

(800, 9)

### drop = 'first':

 - To eliminate multicollinearity from the data.

In [35]:
ohe = OneHotEncoder(sparse_output=False,dtype=np.int32,drop='first')

ohe.fit(X_train[['gender','race/ethnicity','lunch']])
new_X_train = ohe.transform(X_train[['gender','race/ethnicity','lunch']])
new_X_test = ohe.transform(X_test[['gender','race/ethnicity','lunch']])

new_X_train

array([[0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1],
       ...,
       [0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1]], dtype=int32)

In [36]:
new_X_train.shape

(800, 6)