In [4]:
# Q1
import numpy as np
arr = np.random.randint(1, 101, 10)
even_indices = np.where(arr % 2 == 0)[0]
print("Array:", arr)
print("Indices of even elements:", even_indices)

Array: [24 35 84 37 12  3  6 89 81 74]
Indices of even elements: [0 2 4 6 9]


In [5]:
# Q2
import numpy as np
matrix = np.random.rand(4, 4)
np.fill_diagonal(matrix, np.sqrt(np.diagonal(matrix)))
print("Modified Matrix:")
print(matrix)

Modified Matrix:
[[0.68242864 0.74011573 0.0204582  0.60468308]
 [0.81929206 0.36907187 0.07376239 0.62966241]
 [0.94535475 0.24815274 0.64057596 0.49144161]
 [0.16077812 0.35819627 0.88682144 0.60099122]]


In [6]:
# Q3
import numpy as np
arr = np.arange(1, 21).reshape(4, 5)
row_sums = arr.sum(axis=1)
col_sums = arr.sum(axis=0)
print("Matrix:")
print(arr)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row sums: [15 40 65 90]
Column sums: [34 38 42 46 50]


In [7]:
# Q4
import numpy as np
arr = np.random.rand(10)
normalized_arr = (arr - np.mean(arr)) / np.std(arr)
print("Original Array:", arr)
print("Normalized Array:", normalized_arr)

Original Array: [0.36802052 0.95293685 0.29981469 0.80157874 0.40568477 0.76012823
 0.74280392 0.18775165 0.69296063 0.92648258]
Normalized Array: [-0.94523617  1.30412778 -1.20752963  0.72206251 -0.8003939   0.56265974
  0.49603711 -1.63848114  0.3043589   1.2023948 ]


In [8]:
# Q5
import numpy as np
arr = np.random.randint(-100, 101, 20)
arr = np.where(arr < 0, np.abs(arr), np.where(arr > 50, 50, arr))
print("Modified Array:", arr)

Modified Array: [ 37   9  48  13  50  48  37  56  37  30  37 100  50  90  29  40  50  50
  56  50]


In [9]:
# Q6
import numpy as np
arr = np.random.randint(1, 101, (3, 4, 5))
means = arr.mean(axis=(1, 2))
print("3D Array:")
print(arr)
print("Mean values along each 2D slice:", means)

3D Array:
[[[32 61 76 42 71]
  [11 71 57 87 86]
  [24 38 97 80 40]
  [50  1 27 63 30]]

 [[85  1 85 30 52]
  [65 93 97 67 74]
  [27 58 95 78 23]
  [12 40 72 72 24]]

 [[72 68  4 60 88]
  [90 89 76 83 49]
  [52 84 51 37 23]
  [ 9  1 36 20 46]]]
Mean values along each 2D slice: [52.2 57.5 51.9]


In [10]:
# Q7
import numpy as np
def elementwise_division(arr1, arr2):
    return np.where(arr2 != 0, arr1 / arr2, 0)

arr1 = np.random.randint(1, 10, (2, 2))
arr2 = np.random.randint(0, 10, (2, 2))
result = elementwise_division(arr1, arr2)
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Result of element-wise division:")
print(result)

Array 1:
[[9 8]
 [1 5]]
Array 2:
[[3 2]
 [1 6]]
Result of element-wise division:
[[3.         4.        ]
 [1.         0.83333333]]


In [11]:
# Q8
import numpy as np
size = 5
center = size // 2
matrix = np.fromfunction(lambda i, j: np.abs(i - center) + np.abs(j - center), (size, size))
print("Manhattan Distance Matrix:")
print(matrix)

Manhattan Distance Matrix:
[[4. 3. 2. 3. 4.]
 [3. 2. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 2. 3.]
 [4. 3. 2. 3. 4.]]


In [12]:
# Q9
import numpy as np
arr = np.random.randint(1, 101, (6, 6))
arr[arr % 3 == 0] = -1
print("Modified Matrix:")
print(arr)

Modified Matrix:
[[-1 68 76 68 -1 50]
 [44 -1 10 10 25 55]
 [68 56 37 67 16 38]
 [ 2  5 -1 73 -1 -1]
 [-1  5 -1 95 44 -1]
 [29 -1 44 -1 -1  1]]


In [13]:
# Q10
import numpy as np
arr = np.random.randint(1, 10, (2, 3, 4))
flattened_ravel = arr.ravel()
flattened_flatten = arr.flatten()
print("Original Array:")
print(arr)
print("Flattened using ravel:", flattened_ravel)
print("Flattened using flatten:", flattened_flatten)

Original Array:
[[[3 1 4 2]
  [3 1 1 1]
  [3 8 8 9]]

 [[2 3 8 7]
  [9 3 9 5]
  [8 8 9 2]]]
Flattened using ravel: [3 1 4 2 3 1 1 1 3 8 8 9 2 3 8 7 9 3 9 5 8 8 9 2]
Flattened using flatten: [3 1 4 2 3 1 1 1 3 8 8 9 2 3 8 7 9 3 9 5 8 8 9 2]


In [14]:
# Q11
import numpy as np
arr = np.random.randint(1, 10, (3, 3))
flipped = np.flip(np.flip(arr, axis=0), axis=1)
print("Original Array:")
print(arr)
print("Flipped Array:")
print(flipped)

Original Array:
[[2 3 8]
 [6 3 9]
 [4 5 3]]
Flipped Array:
[[3 5 4]
 [9 3 6]
 [8 3 2]]


In [15]:
# Q12
import numpy as np
arr = np.random.randint(1, 101, 30)
partitioned = np.array_split(np.sort(arr), 3)
print("Original Array:", arr)
print("Partitioned Arrays:")
for part in partitioned:
    print(part)

Original Array: [32 84 53 30 21 17 39 56 15 26  8 22 72 20 42 94 33 28  6 96 79 37 11 16
 55 98 69 15 82 49]
Partitioned Arrays:
[ 6  8 11 15 15 16 17 20 21 22]
[26 28 30 32 33 37 39 42 49 53]
[55 56 69 72 79 82 84 94 96 98]


In [16]:
# Q13
import numpy as np
arr = np.random.randint(1, 101, 15)
top_three = np.partition(arr, -3)[-3:]
print("Array:", arr)
print("Top three maximum values:", top_three)

Array: [95 31 29 37 75 50 85 34 60 41 70 86  4 10 84]
Top three maximum values: [85 86 95]


In [17]:
# Q14
import numpy as np
scores = np.random.randint(0, 101, (10, 3))
highest_scorer = np.argmax(scores.sum(axis=1))
print("Scores Matrix:")
print(scores)
print("Highest scoring student index:", highest_scorer)

Scores Matrix:
[[19 14 68]
 [88 55 78]
 [27 16 92]
 [84 29 88]
 [58 66 46]
 [30  4  5]
 [67  2 20]
 [24  4  2]
 [59 60 77]
 [ 2  6 76]]
Highest scoring student index: 1


In [18]:
# Q15
import numpy as np
def find_pairs(arr, target):
    pairs = []
    for i in range(len(arr)):
        for j in range(i + 1, len(arr)):
            if arr[i] + arr[j] == target:
                pairs.append((i, j))
    return pairs

arr = np.random.randint(1, 10, 10)
target_sum = 10
pairs = find_pairs(arr, target_sum)
print("Array:", arr)
print("Pairs with target sum", target_sum, ":", pairs)

Array: [4 5 4 9 4 9 4 5 9 9]
Pairs with target sum 10 : [(1, 7)]


In [19]:
# Q16
import numpy as np
arr = np.arange(1, 37).reshape(6, 6)
last_row = arr[-1, :]
last_col = arr[:, -1]
print("Matrix:")
print(arr)
print("Last row:", last_row)
print("Last column:", last_col)

Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Last row: [31 32 33 34 35 36]
Last column: [ 6 12 18 24 30 36]


In [20]:
# Q17
import numpy as np
arr = np.random.randint(1, 101, (5, 5))
center_submatrix = arr[1:4, 1:4]
print("Original Matrix:")
print(arr)
print("Center 3x3 Sub-Matrix:")
print(center_submatrix)

Original Matrix:
[[42 65 89 34 20]
 [99 49 84 97 18]
 [60 26 60 93 90]
 [15 19 45 64 96]
 [66 55 95 82 63]]
Center 3x3 Sub-Matrix:
[[49 84 97]
 [26 60 93]
 [19 45 64]]


In [21]:
# Q18
import numpy as np
arr = np.arange(1, 17).reshape(4, 4)
reversed_last_two = arr[-2:, ::-1]
print("Original Matrix:")
print(arr)
print("Reversed Last Two Rows:")
print(reversed_last_two)

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Reversed Last Two Rows:
[[12 11 10  9]
 [16 15 14 13]]
