<font size=7><b> Numpy

<font size=6> *What is NumPy?*

<font size=4>- NumPy is a Python library used for working with arrays.

<font size=4>- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

<font size=4>- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

<font size=4>- NumPy stands for Numerical Python.

<font size=6> *Why Use NumPy?*

<font size=4>-In Python we have lists that serve the purpose of arrays, but they are slow to process.
    

<font size=4>-NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

<font size=4>-The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with **ndarray** very easy.

 <font size=4>-Arrays are very frequently used in data science, where speed and resources are very important.</font>

<font size=6> *Why is NumPy Faster Than Lists?*

<font size=4>-NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

<font size=4>-This behavior is called locality of reference in computer science.

<font size=4>-This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

<font size=6>*Which Language is NumPy written in?*

<font size=4>NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

<font size=6> *Installation of NumPy*

<font size=4> If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

<font size=4> Install it using this command:

In [1]:
! pip install numpy

<font size=4>If this command fails, then use a python distribution that already has NumPy installed like, Anaconda, Spyder etc.

<font size=6> *Import NumPy*

<font size=4>Once NumPy is installed, **import** it in your applications by adding the import keyword:

In [2]:
import numpy

<font size=6> *NumPy as np*

<font size=4>NumPy is usually imported under the **np** alias.
    
<font size=4>  Create an alias with the **as** keyword while importing:

In [2]:
import numpy as np

<font size=6> *Creating an array*

<font size=4>NumPy is used to work with arrays. The array object in NumPy is called **ndarray**

<font size=4>We can create a NumPy **ndarray** object by using the **array()** function.

In [5]:
# Using array function to create an array.

np.array((1, 2, 3, 4, 5))

array([1, 2, 3, 4, 5])

In [4]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


<font size=5> ***numpy.arange()***

<font size=4>The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop) 

In [ ]:
a = np.arange(4)
a

[0 1 2 3]


In [ ]:
#Creates array with random values
a1=np.random.random((4))#creates array with 4 random vals
a1

array([0.50034303, 0.43869076, 0.64937183, 0.48399565])

In [ ]:
# Create an array of 10 random floats in the half-open interval [0.0, 1.0)
array_random = np.random.random(10)
print(array_random)

[0.94364428 0.45366381 0.77078813 0.84968144 0.33012881 0.03830811
 0.35020411 0.4997248  0.9193609  0.48061043]


In [ ]:
# Create a 2D array of shape (3, 4) with random values
array_random_2d = np.random.random((3, 4))
print(array_random_2d)


[[0.50879965 0.88738081 0.48700286 0.04517143]
 [0.69375601 0.82087005 0.14741679 0.3827137 ]
 [0.17686659 0.73800149 0.14666863 0.0428239 ]]


In [ ]:
x1=np.random.randint(50,size=6)#one dimensional array
x2=np.random.randint(10,size=(3,4))#two dimensional array
x3=np.random.randint(10,size=(3,4,5))#three dimensional array
print(x1)
print()
print(x2)
print()
print(x3)

[ 2 45 11 38 31 34]

[[1 8 2 3]
 [6 5 0 2]
 [1 6 1 8]]

[[[0 4 0 4 3]
  [4 7 1 5 2]
  [0 4 3 1 3]
  [8 2 9 5 9]]

 [[1 6 3 4 1]
  [7 1 4 5 2]
  [9 8 9 8 3]
  [8 6 5 1 0]]

 [[4 6 0 9 5]
  [6 4 5 0 4]
  [1 3 4 4 8]
  [7 8 1 5 0]]]


<font size=6> *Dimensions in Arrays*

<font size=4>A dimension in arrays is one level of array depth (nested arrays).

<font size=5>***0-D Arrays***

<font size=4>0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [6]:
arr = np.array(42)
print(arr)
print('Dimensions :',arr.ndim)

42
Dimensions : 0


<font size=5>***1-D Arrays***

<font size=4>An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

In [7]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print('Dimensions :',arr.ndim)

[1 2 3 4 5]
Dimensions : 1


<font size=5>***2-D Arrays***

<font size=4>An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

In [6]:
#nested sequence will be convertd into a multidimensional array
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)
print('Dimensions :',arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
Dimensions : 2


<font size=5>***3-D arrays***

<font size=4>An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.

In [9]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)
print('Dimensions :',arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimensions : 3


<font size=5>***Higher Dimensional Arrays***

<font size=4>An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


<font size=5> ***Random***

In [ ]:
print(np.arange(1, 2, 0.1))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [ ]:
a=np.arange(3,9,2)
print(a)

[3 5 7]


<font size=6> *NumPy Array Shape*

<font size=4>NumPy arrays have an attribute called ***shape*** that returns a tuple with each index having the number of corresponding elements.

In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


<font size=4>The example above returns ***(2, 4)***, which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

<font size=6> *Reshaping arrays*

<font size=4>-Reshaping means changing the shape of an array.

<font size=4>-The shape of an array is the number of elements in each dimension.

<font size=4>-By reshaping we can add or remove dimensions or change number of elements in each dimension.

<font size=5> ***Reshape From 1-D to 2-D***

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(4,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 6)
print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(6, 2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


<font size=5> ***Reshape From 1-D to 3-D***

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 2, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2, 3)
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


<font size=5> ***Can We Reshape Into any Shape?***

<font size=4>-Yes, as long as the elements required for reshaping are equal in both shapes.
    
<font size=4>-We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
    
<font size=4>-Example:-
Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

### Indexing in numpy array

In [3]:
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(24).reshape(2,4,3)

In [7]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 1D array indexing. -> As with lists , single element indexing is 0-based and accepts negative indices for indexing from end of the array
print(arr1[0])
print(arr1[2])
print(arr1[-1])
print(arr1[-5])

0
2
9
5


In [20]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
# 2D array Indexing -> Individual element of a multi-dimensional array are accessed using multiple indices

print(arr2[1][2]) # -> accessing an element from 2D array
print(arr2[1,2])
print(arr2[-1,2])

6
6
10


In [26]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [39]:
# 3D array Indexing 

print(arr3[0][0][0])
print(arr3[1][3][2])
print(arr3[-1][-2][-1])

# Another way of accessing element in 3D array
print(arr3[0,0,0])
print(arr3[-1,2,0])
print(arr3[-1,0,-2])

0
23
20
0
18
13


## Slicing in numpy array

In [41]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# Slicing in 1D array (same as python list slicing).
print(arr1[::])
print(arr1[::-1])
print(arr1[2::2])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6 8]


In [48]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
# Slicing in 2D array

print(arr2[0,:])
print()
print(arr2[:,0])
print()
print(arr2[1:,1:])
print()
print(arr2[::2,:2:])

[0 1 2 3]

[0 4 8]

[[ 5  6  7]
 [ 9 10 11]]

[[0 1]
 [8 9]]


In [61]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [73]:
# Slicing in 3D array
print(arr3[0],end='\n\n')
print(arr3[0,0],end='\n\n')
print(arr3[1,:3],end='\n\n')
print(arr3[0,:2,::2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[12 13 14]
 [15 16 17]
 [18 19 20]]

[[0 2]
 [3 5]]


<font size=7> NumPy Data Types

<font size=5> ***Data Types in NumPy***

<font size=4>NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

<font size=4>Below is a list of all data types in NumPy and the characters used to represent them.
    
<font size=4>***i - integer***

<font size=4>***b - boolean***
    
<font size=4>***u - unsigned integer***
    
<font size=4>***f - float***
    
<font size=4>***c - complex float***
    
<font size=4>***m - timedelta***
    
<font size=4>***M - datetime***
    
<font size=4>***O - object***
    
<font size=4>***S - string***
    
<font size=4>***U - unicode string***
    
<font size=4>***V - fixed chunk of memory for other type ( void )***

<font size=5> ***Data Types in NumPy***

<font size=4>The NumPy array object has a property called dtype that returns the data type of the array:

In [29]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [20]:
arr = np.array([1.0, 2.0, 3.34, 4.534])
print(arr.dtype)

float64


In [21]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


<font size=5> ***Creating Arrays With a Defined Data Type***

<font size=4>We use the **array()** function to create arrays, this function can take an optional argument: **dtype** that allows us to define the expected data type of the array elements:
    
<font size=4>For **i**, **u**, **f**, **S** and **U** we can define size as well.

In [22]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [25]:
arr = np.array([1, 2, 3, 4], dtype='i2')
print(arr)
print(arr.dtype)

[1 2 3 4]
int16


<font size=4>If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [26]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

<font size=4>**dtype=np.int8** in NumPy, you're specifying that each element of the array should be stored as an 8-bit signed integer. This data type can represent integers in the range of -128 to 127.

In [73]:
arr=np.array(range(40),dtype=np.int8)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39], dtype=int8)

<font size=4>**dtype=np.uint8** specifies that the data type of the array elements is uint8, which is an 8-bit unsigned integer.

In [76]:
arr=np.array(range(256),dtype=np.uint8)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

<font size=4>**dtype=np.int_** specifies that the data type of the array elements is **int_**, which is a NumPy integer type.

In [79]:
arr=np.array(range(150),dtype=np.int_)
print(arr)
arr.dtype#by default dtype is int32

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149]


dtype('int32')

<font size=5> ***Converting Data Type on Existing Arrays***

<font size=4>- The best way to change the data type of an existing array, is to make a copy of the array with the **astype()** method.

<font size=4>- The **astype()** function creates a copy of the array, and allows you to specify the data type as a parameter.

<font size=4>-The data type can be specified using a string, like **'f'** for float, **'i'** for integer etc. or you can use the data type directly like float for float and int for integer.

In [25]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [26]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [27]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [28]:
numeric_string=np.array(['1.25','9.6','42'],dtype=np.string_)
print(numeric_string)
print(numeric_string.dtype)
numeric_string=numeric_string.astype(float)
print(numeric_string)
print(numeric_string.dtype)

[b'1.25' b'9.6' b'42']
|S4
[ 1.25  9.6  42.  ]
float64


<font size=4>You can explicitly convert or cast an array from one dtype to another using the **astype** method of ndarray

In [85]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [86]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

<font size=4>if you have an array of string represting numbers,you can use astype to convert them to numeric form:

In [95]:
numeric_string=np.array(['1.25','9.6','42'],dtype=np.string_)

In [96]:
numeric_string.dtype

dtype('S4')

In [97]:
numeric_string=numeric_string.astype(float)
numeric_string

array([ 1.25,  9.6 , 42.  ])

In [98]:
numeric_string

array([ 1.25,  9.6 , 42.  ])

<font size=6> *NumPy Array Attributes*

<font size=4>-A numpy array has several attributes that indicate the element type,element size,shape of arrays,size of arrays,etc
    
<font size=4>-We can obtain the types of element present in a numpy array their aizes,their location in,memory etc.
    
<font size=4>-Attributes of arrays determine the size ,shape,memory,and data types of array

In [26]:
a1=np.array([1,2,3,4])
a2=np.array([1.1,2.2,3.3,4.4])

# Here "dtypes" specifies the type of element contained in the array
print(a1.dtype)
print(a2.dtype)

# Number of bytes occupied by individual array element are available through "itemsize"
print(a1.itemsize)
print(a2.itemsize)

# Number of bytes occupied by entire are available through "itemsize"
print(a1.nbytes)
print(a2.nbytes)

# "data" gives the address in memory where the array begins(often called base address)
print(a1.data)
print(a2.data)

# "strides" indicates the number of bytes that should be added to base address to reach the next array element
print(a1.strides)
print(a2.strides)

int32
float64
4
8
16
32
(4,)
(8,)


In [27]:
# Attributes "ndim","shape",and "size" yield the number of dimensions in the array the shape of the array and the number of element in it

a1=np.array([1,2,3,4])
a2=np.array([[1,2,3,4],[5,6,7,8]])

# ndim
print(a1.ndim)
print(a2.ndim)

# shape
print(a1.shape)
print(a2.shape)

# size
print(a1.size)
print(a2.size)

1
2
(4,)
(2, 4)
4
8


<font size=6> *Numpy Array Functions*

<font size=5> ***Zeroes***

In [29]:
# zeros create arrays of 0s
print(np.zeros(10))
print()
print(np.zeros((3,6)))
print()
print(np.zeros((2,3,2))) #here 2 is representing total numer of array and 3 is represting number of rows and 2 is represting number of columns

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


<font size=5> ***Ones***

In [30]:
# Ones create arrays of 1s
print(np.ones(10))
print()
print(np.ones((3,6)))
print()
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


<font size=5> ***Empty array***

In [12]:
#We can create empty arrays which are filled with garbage values
np.empty((2,3,2))

array([[[4.45057637e-308, 1.78021527e-306],
        [8.45549797e-307, 1.37962049e-306],
        [1.11260619e-306, 1.78010255e-306]],

       [[9.79054228e-307, 4.45057637e-308],
        [8.45596650e-307, 9.34602321e-307],
        [4.94065646e-322, 0.00000000e+000]]])

In [20]:
np.empty((3,4))

array([[4.45057637e-308, 1.78021527e-306, 8.45549797e-307,
        1.37962049e-306],
       [1.11260619e-306, 1.78010255e-306, 9.79054228e-307,
        4.45057637e-308],
       [8.45596650e-307, 9.34602321e-307, 4.94065646e-322,
        0.00000000e+000]])

<font size=5> ***eye function()***

<font size=4>The **numpy.eye()** function in Python is used to return a two-dimensional array with ones (1) on the diagonal and zeros (0) elsewhere.

<font size=5>*Parameters*
    
<font size=4>The **numpy.eye()** function takes the following parameter values:

<font size=4>-**N**: This represents the number of rows we want in the output array.
    
<font size=4>-**M**: This represents the number of columns we want in the output array. This is optional.
    
<font size=4>-**k**: This represents the index of the diagonal. **0** is the default value and the main diagonal. This is optional.
    
<font size=4>-**dtype**: This represents the data type of array to be returned. This is optional.
    
<font size=4>-**order**: This represents whether the output should be stored in **C** or **F** order in memory. This is optional.
    
<font size=4>-**like**: This is the array prototype or **array_like** object.

<font size=5>*Syntax*
    
<font size=4>numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

In [43]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [74]:
#both are same
print(np.eye(3))
print()
print(np.eye(3,3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [47]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [48]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#use of dtype with eye function
print(np.eye(2,2,dtype=int))
print()
print(np.eye(5,3,dtype=float))

[[1 0]
 [0 1]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
# An array with 3 rows with with the ones starting at the index i.e fron the second column
myarray = np.eye(3, k=0)
print(myarray)
print()
print(np.eye(3, k=1))
print()
print(np.eye(5, k=0))
print()
print(np.eye(5, k=1))
print()
print(np.eye(5, k=2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<font size=4>**C-Order (Row-major Order)**:In C-order (also known as row-major order), the array is stored in memory row by row. This means that elements of the same row are contiguous in memory.

<font size=4>**F-Order (Fortran-major Order)**: In F-order (also known as column-major order), the array is stored in memory column by column. This means that elements of the same column are contiguous in memory.

In [27]:
# Create a 3x3 identity matrix in C-order
eye_c = np.eye(3, order='C')
print("C-order:\n", eye_c)
print("C-order flags:", eye_c.flags)

# Create a 3x3 identity matrix in F-order
# eye_f = np.eye(3, order='F')
# print("F-order:\n", eye_f)
# print("F-order flags:", eye_f.flags)


C-order:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
C-order flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



<font size=5> ***identity() function***

<font size=4>identity matrix is a square matrix in which all the element of the main diagonal are equal to **1** and all othere element are equal to **0**. the **identity ()** function return the identity array.The **identity()** ***function*** from **numpy** library is used to return the identity matrix.

<font size=5>Syntax
    
<font size=4>identity(n, dtype=float, like=None)

<font size=5>*Parameter value*

<font size=4>The **identity() function** takes the following parameter values:

<font size=4>**n**: This represents the number of rows in the output.
    
<font size=4>**dtype**: This represents the data type of the output matrix. This is optional and its default type is float.

<font size=4>**like**: This represents the matrix-like object or the prototype.

In [57]:
np.identity(2)#default data as float

array([[1., 0.],
       [0., 1.]])

In [78]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [77]:
np.identity(2,3)

TypeError: Cannot interpret '3' as a data type

<font size=5> ***numpy.full()***

<font size=4>The **numpy.full()** function is used to create a new array of the seprate filled with a specified valueThe **numpy.full()** function is used to return a new array of a given shape and data type filled with fill_value.

<font size=5>*Syntax*
    
<font size=4>numpy.full(shape, fill_value, dtype=None, like=None)

<font size=5>*Parameters*
    
<font size=4>The **numpy.full()** function takes the following parameter values:

<font size=4>-**shape**: This represents the shape of the desired array.
    
<font size=4>-**fill_value**: This represents the fill value.

<font size=4>-**dtype**: This represents the data type of the desired array. This is an optional parameter.

<font size=4>-**like**: This represents the prototype or the array_like object.

In [64]:
np.full(3,12)

array([12, 12, 12])

In [65]:
np.full([2,2],3)

array([[3, 3],
       [3, 3]])

In [66]:
np.full((3,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [67]:
np.full((3,3),55,dtype=float)

array([[55., 55., 55.],
       [55., 55., 55.],
       [55., 55., 55.]])

<font size=5> ***full_like() function***

<font size=4>In Python, the **numpy.full_like()** ***function*** is used to return an entire array with the same shape and type as the array that was passed to it.

<font size=5>*Syntax*
    
<font size=4>numpy.full_like(a, fill_value)

<font size=5>*Parameter value*
    
<font size=4>The **numpy.full_like()** function takes the following parameter values:

<font size=4>**a**: This represents the array_like object or prototype of the array that needs to be created.

<font size=4>**fill_value**: This represents the fill value.

<font size=4>The **numpy.full_like()** function returns an array of **fill_value**, with the same shape and data type as the **array_like** parameter that is passed to it.

In [71]:
# creating an array_like 
thisarray = np.arange(4, dtype = int)

# implementing the numpy.ones_like() function 
myarray = np.full_like(thisarray, 10)


# printing the two arrays
print(thisarray)
print(myarray)

[0 1 2 3]
[10 10 10 10]


In [70]:
a=np.arange(5)
print(a.dtype)
print(np.full_like(a,3))
print(np.full_like(a,1.2))#by default a is integer
print()
b=a.astype(float)
print(np.full_like(b,1.2))
print(np.full_like(a,np.nan,dtype=np.double))

int32
[3 3 3 3 3]
[1 1 1 1 1]

[1.2 1.2 1.2 1.2 1.2]
[nan nan nan nan nan]


<font size=6> *Arithmetic operations with numpy array*

<font size=4>You could use arithmetic operators "**+ - * /**" directly between NumPy arrays

<font size=5>***List of Arithmetic Operations***


<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAJMDiUk9yiwoqQ_faxvX9AJ9_ulmQ3AbRrw&s"
     width="600"/>

### Arithmetic operations on 1D Array 

In [85]:
a1 = np.array([1, 3, 5, 7])
b1 = np.array([2, 4, 6, 8])
print(a1)
print(b1)

[1 3 5 7]
[2 4 6 8]


### 1. Scalar operations:

In [115]:
# All Scalar operation on 1D array using operators :
print(a1+5)
print(a1-5)
print(a1*2)
print(a1/2)
print(a1//2)
print(-a1)
print(a1**2)
print(a1%2)

[1 3 5 7]
[ 6  8 10 12]
[-4 -2  0  2]
[ 2  6 10 14]
[0.5 1.5 2.5 3.5]
[0 1 2 3]
[-1 -3 -5 -7]
[ 1  9 25 49]
[1 1 1 1]


In [116]:
# All Scalar operation on 1D array using there built in functions :
print(np.add(a1,5))
print(np.subtract(a1,5))
print(np.multiply(a1,2))
print(np.divide(a1,2))
print(np.floor_divide(a1,2))
print(np.negative(a1))
print(np.power(a1,3))
print(np.mod(a1,2))

[1 3 5 7]
[ 6  8 10 12]
[-4 -2  0  2]
[ 2  6 10 14]
[0.5 1.5 2.5 3.5]
[0 1 2 3]
[-1 -3 -5 -7]
[  1  27 125 343]
[1 1 1 1]


### 2. Vector Operations:

In [117]:
# All Vector operations on 1D array using operators :
print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)
print(a1//b1)
print(a1**b1)
print(a1%b1)

[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[0 0 0 0]
[      1      81   15625 5764801]
[1 3 5 7]


In [118]:
# All Vector operations on 1D array using there built in functions :
print(np.add(a1,b1))
print(np.subtract(a1,b1))
print(np.multiply(a1,b1))
print(np.divide(a1,b1))
print(np.floor_divide(a1,b1))
print(np.power(a1,b1))
print(np.mod(a1,b1))

[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[0 0 0 0]
[      1      81   15625 5764801]
[1 3 5 7]


### Arithmetic operations on 2D array

In [124]:
a2 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)
print(a2)
print()
print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [132]:
# All Scalar operation on 2D array using operators :
print(a2+5,end='\n\n')
print(a2-5,end='\n\n')
print(a2*2,end='\n\n')
print(a2/2)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[-5 -4 -3 -2]
 [-1  0  1  2]
 [ 3  4  5  6]]

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [133]:
# Other Operations:

print(a2//2,end='\n\n')
print(-a2,end='\n\n')
print(a2**2,end='\n\n')
print(a2%2)

[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]

[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [136]:
# All Scalar operation on 2D array using there built in functions :
print(np.add(a2,5),end='\n\n')
print(np.subtract(a2,5),end='\n\n')
print(np.multiply(a2,2),end='\n\n')
print(np.divide(a2,2))

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[-5 -4 -3 -2]
 [-1  0  1  2]
 [ 3  4  5  6]]

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [135]:
# Other Operations:

print(np.floor_divide(a2,2),end='\n\n')
print(np.negative(a2),end='\n\n')
print(np.power(a2,3),end='\n\n')
print(np.mod(a2,2))

[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]

[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]

[[   0    1    8   27]
 [  64  125  216  343]
 [ 512  729 1000 1331]]

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [138]:
# All Vector operations on 2D array using operators :
print(a2+b2,end='\n\n')
print(a2-b2,end='\n\n')
print(a2*b2,end='\n\n')
print(a2/b2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [139]:
# Other operations:

print(a2//b2,end='\n\n')
print(a2**b2,end='\n\n')
print(a2%b2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [141]:
# All Vector operations on 1D array using there built in functions :
print(np.add(a2,b2),end='\n\n')
print(np.subtract(a2,b2),end='\n\n')
print(np.multiply(a2,b2),end='\n\n')
print(np.divide(a2,b2))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


In [121]:
x=np.arange(4)

In [122]:
print('x=',x)
print('x+5=',x+5)
print('x-5=',x-5)
print('x*2=',x*2)
print('x/2=',x/2)
print('x//2=',x//2)
print('-x=',-x)
print('x**2=',x**2)
print('x%2=',x%2)

x= [0 1 2 3]
x+5= [5 6 7 8]
x-5= [-5 -4 -3 -2]
x*2= [0 2 4 6]
x/2= [0.  0.5 1.  1.5]
x//2= [0 0 1 1]
-x= [ 0 -1 -2 -3]
x**2= [0 1 4 9]
x%2= [0 1 0 1]


In [123]:
#airthmatic function
print('x=',x)
print(np.add(x,5))
print(np.subtract(x,5))
print(np.multiply(x,2))
print(np.divide(x,2))
print(np.floor_divide(x,2))
print(np.negative(x))
print(np.power(x,3))
print(np.mod(x,2))

x= [0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[ 0 -1 -2 -3]
[ 0  1  8 27]
[0 1 0 1]


## Dot Product

In [142]:
# 1D array, 
arr1 = np.array([9, 10, 20])
arr2 = np.array([2, 5, 7])

np.dot(arr1,arr2)

208

In [146]:
# 2D array,
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12).reshape(4,3)

np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

<font size=6> *Statistical operations with numpy array*

<font size=4>Statistics involves gathering data, analyzing it, and drawing conclusions based on the information collected.
NumPy provides us with various statistical functions that can perform statistical data analysis.



![](https://miro.medium.com/v2/resize:fit:931/1*tA-rwKcxh41ZQVwuI17fTA.png)

In [31]:
x=np.arange(50).reshape(10,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [32]:
np.mean(x)

24.5

In [33]:
np.mean(x,axis=0) # Mean of individual columns.

array([22.5, 23.5, 24.5, 25.5, 26.5])

In [34]:
np.mean(x,axis=1) # Mean of individual rows.

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47.])

In [35]:
# To find mean, we can apply average function also.
np.average(x)

24.5

In [36]:
np.average(x,axis=1) # Gives average of every row in a array

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47.])

In [37]:
np.average(x,axis=0) # Gives average of every column in a array

array([22.5, 23.5, 24.5, 25.5, 26.5])

In [38]:
np.min(x)

0

In [39]:
np.max(x)

49

In [40]:
np.min(x,axis=0) # Gives min value of every column in a array

array([0, 1, 2, 3, 4])

In [41]:
np.min(x,axis=1) # Gives min value of every row in a array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [42]:
np.max(x,axis=0) # Gives max value of every column in a array

array([45, 46, 47, 48, 49])

In [43]:
np.max(x,axis=1) # Gives max value of every row in a array

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [44]:
np.var(x) # The function np.var() in NumPy calculates the variance of the array elements

208.25

In [45]:
np.var(x,axis=0) # Calculates the variance of the array elements in columns 

array([206.25, 206.25, 206.25, 206.25, 206.25])

In [46]:
np.var(x,axis=1) # Calculates the variance of the array elements in rows 

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [47]:
np.sum(x) # calculates the sum of the array elements  

1225

In [48]:
np.sum(x,axis=0) # calculates the sum of the array elements in columns 

array([225, 235, 245, 255, 265])

In [49]:
np.sum(x,axis=1)#calculates the sum of the array elements in rows 

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235])

<font size=4>A percentile is a measure used in statistics to express the relative standing of a value within a dataset. It indicates the value below which a given percentage of observations fall. For example, the 25th percentile (also known as the first quartile) is the value below which 25% of the data falls.

In [50]:
p25=np.percentile(x,25)
p50=np.percentile(x,50)
p75=np.percentile(x,75)
p100=np.percentile(x,100)
print()
print("25th Percentile:",p25)
print("50th Percentile:",p50)
print("75th Percentile:",p75)
print("100th Percentile:",p100)


25th Percentile: 12.25
50th Percentile: 24.5
75th Percentile: 36.75
100th Percentile: 49.0


## Iterating through an array

In [148]:
# 1D array
a1 = np.array([2,4,5,7,8,4,1,5,6])
for i in a1:
    print(i)

2
4
5
7
8
4
1
5
6


In [155]:
# 2D array
a2 = np.arange(20).reshape(4,5)
for i in a2:
    print(i,end='\n\n')

[0 1 2 3 4]

[5 6 7 8 9]

[10 11 12 13 14]

[15 16 17 18 19]



In [154]:
# 3D array 
a3 = np.arange(20).reshape(5,2,2)
for i in a3:
    print(i,end='\n\n')

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

[[ 8  9]
 [10 11]]

[[12 13]
 [14 15]]

[[16 17]
 [18 19]]



In [156]:
# np.nditer function
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Some Other reshaping functions.

In [179]:
# transpose() -> Convert row to column and column to row.

arr2 = np.arange(12).reshape(4,3) # 2D array.
print(arr2)
print("Shape of array :",arr2.shape,end='\n\n')

arr2 = np.transpose(arr2)
# arr2_new = arr2.T # Another way of transposing the array
print(arr2)
print("Shape of new array after transpose :",arr2.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape of array : (4, 3)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Shape of new array after transpose : (3, 4)


In [178]:
# ravel() -> Convert n dimension array into 1D array.

arr2 = np.arange(12).reshape(4,3) # 2D array.
print(arr2)
print("Shape of array :",arr2.shape)
print("Number of dimensions :",arr2.ndim,end='\n\n')

arr2 = np.ravel(arr2)
print(arr2)
print("Shape of new array after reval() :",arr2.shape)
print("Number of dimensions after ravel() :",arr2.ndim)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape of array : (4, 3)
Number of dimensions : 2

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape of new array after reval() : (12,)
Number of dimensions after ravel() : 1


## Stacking of numpy array.

In [181]:
s1 = np.arange(12).reshape(3,4)
s2 = np.arange(12,24).reshape(3,4)

In [183]:
s1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [185]:
# horizontal stacking
s3 = np.hstack((s1,s2))
s3

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [186]:
# vertical stacking
s4 = np.vstack((s1,s2))
s4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Spliting of numpy array.

In [194]:
# Horizontal Spliting:
np.hsplit(s3,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [195]:
a,b = np.hsplit(s3,2)
print(a,end='\n\n')
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [196]:
# Vertical Spliting
np.vsplit(s4,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [197]:
c,d = np.vsplit(s4,2)
print(c,end='\n\n')
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [199]:
# Unequal dividion results in error
np.hsplit(s4,3)

ValueError: array split does not result in an equal division