# Numpy Speacial functions

In [95]:
import numpy as np

## Methods:
- sort
- append
- arange
- concatenate
- array
- unique
- expand_dims
- where
- argmax
- argmin
- cumsum
- cumprod
- percentile
- median
- histogram
- corrcoef
- flip
- put
- delete
- union1d
- intersect1d
- setdiff1d
- setxor1d
- clip

### 1. np.sort

Return a sorted copy of an array.

Link of documentation -> https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [5]:
# code
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [6]:
print(a)
print(b)

[70 18 81 21 30 41  7 48  7 84 95 26 37 18  5]
[[84 31 29  8]
 [71 73  1 15]
 [85 46  5 99]
 [63 66  8 55]
 [18 83 15 42]
 [10 13 31 88]]


In [7]:
# np.sort()

In [8]:
# np.sort() -> axis parameter

### 2. np.append

The numpy.append() appends values along the mentioned axis at the end of the array

Link of documention -> https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# np.append()

In [ ]:
# append one element

In [10]:
# np.append() -> axis parameter (append multiple elements row and column wise)

### 3. np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [11]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
# np.concatenate()   # axis=0

In [13]:
# np.concatenate()   # axis=1

### 4. np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# np.unique()

### 5. np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [35]:
# code
arr = np.arange(12,19)
print(arr)
print(arr.shape)

[12 13 14 15 16 17 18]
(7,)


In [17]:
# axis=0

In [18]:
# axis=1

### 6. np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [38]:
# find all indices with value greater than 30

# np.where()

In [39]:
# replace all values > 30 with -1 using only where()


### 7. np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [40]:
# np.argmax()   # axis=0

In [41]:
# np.argmax()   # axis=1

### 8. np.argmin

In [42]:
# np.argmin()

### 9. np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [43]:
# np.cumsum() -> array


In [44]:
# np.cumsum() -> matrix


In [45]:
# np.cumsum()   # axis=1


In [46]:
# np.cumsum()   # axis=0


### 10. np.cumprod

In [47]:
# np.cumprod()


### 11. np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [49]:
# np.percentile()


In [48]:
# np.median(arr) and np.percentile(arr,50) gives same output


### 12. np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [50]:
# np.histogram() 


In [51]:
# -> bins parameter

### 13. np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [52]:
Marks = np.array([80,90,99,20,5])
atterndence = np.array([60,50,25,80,90])

# np.corrcoef()

### 14. np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [55]:
# np.isin()


In [56]:
sample = [10,20,30,40,50,60,70,80,90,100]

# arr[np.isin(arr,sample)]

### 15. np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [64]:
# np.flip()    # for array

arr1 = np.arange(45,55)
arr1

array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [68]:
# np.flip()    # for matrix

arr2 = np.arange(45,60).reshape(3,5)
arr2

array([[45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [59]:
# np.flip()    # axis=1


In [60]:
# np.flip()    # axis=0


### 16. np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [69]:
# np.put()


### 17. np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [72]:
# np.delete()   # one element deletion


In [73]:
# np.delete()   # multiple element deletion


### 18. Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [86]:
# np.union1d()

In [87]:
# np.intersect1d()

In [88]:
# np.setdiff1d()

In [89]:
# np.setxor1d()

In [91]:
# np.in1d()


# m[np.in1d(m,1)]

### 19. np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [92]:
# np.clip() -> parameter: arr_min= , arr_max=

In [ ]:
# 20. np.swapaxes

In [ ]:
# 21. np.uniform

In [ ]:
# 22. np.count_nonzero

In [ ]:
# 23. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 24. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [94]:
# 25. np.allclose and equals