## Numpy Assignement 3 Solutions:

In [19]:
import numpy as np

Q1. Write a python program which takes dictionary as an input and convert it
into a numpy array.

In [4]:
# 1.

my_dict = {'a': 1, 'b': 2, 'c': 3}
array = np.array(list(my_dict.items()))

print("Converted NumPy Array:\n", array)

Converted NumPy Array:
 [['a' '1']
 ['b' '2']
 ['c' '3']]


Q2. Given a 3D array x of shape (2, 3, 4) and a 2D array y of shape (3, 4). Write
a NumPy program to add them using broadcasting

In [5]:
#2. 

x = np.random.randint(1, 10, (2, 3, 4))
y = np.random.randint(1, 10, (3, 4))

result = x + y

print("Result of Broadcasting addition:\n", result)

Result of Broadcasting addition:
 [[[10 13 18 10]
  [15 14 10  4]
  [11 14  8 14]]

 [[ 5 13 13 15]
  [17 10  8 12]
  [16  7 14 15]]]


Q3. Write a python program which finds the nearest element in the array to a    
given integer.    
Inputs: a=23 and array - [10 17 24 31 38 45 52 59].    
Expected Output: Nearest element is 24    

In [11]:
# 3. 

a = 23
array = np.array([10, 17, 24, 31, 38, 45, 52, 59])

nearest_element = array[np.abs(array - a).argmin()]

print("Nearest element to", a, "is", nearest_element)


Nearest element to 23 is 24


Q4. Write a python program to replace multiples of 3 or 5 as 0 in the given     
array.     
Input: arr=[1 2 3 4 5 6 7 9]     
Expected Output: [1 2 0 4 0 0 7 0]     


In [12]:
# 4. 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 9])
arr[(arr % 3 == 0) | (arr % 5 == 0)] = 0

print("Updated Array:", arr)

Updated Array: [1 2 0 4 0 0 7 0]


Q5. Solve the give problem using fancy Indexing:     
1. Double the array elements at given indexes     
Given:     
arr = np.arrange(10)     
indexes = [0,3,4,9]     
Expected Output: [ 0 1 2 6 8 5 6 7 8 18]     

In [15]:
# 5.1

arr = np.arange(10)
indexes = [0, 3, 4, 9]

print("Original array", arr)

arr[indexes] *= 2

print("Updated Array after doubling:", arr)

Original array [0 1 2 3 4 5 6 7 8 9]
Updated Array after doubling: [ 0  1  2  6  8  5  6  7  8 18]


Using a given array make a different array as in below example    
Given:    
array = [1,2,3]    
result array -> [1 1 1 2 2 2 3 3 3]    
• Internal repeation should be as length of the array.    

In [16]:
# 5.2 

array = [1, 2, 3]
result = []

for element in array:
    for i in range(len(array)):
        result.append(element)

print("Repeated Array:", result)


Repeated Array: [1, 1, 1, 2, 2, 2, 3, 3, 3]


You are given an array which is having some nan value. You job is to fill    
those nan values with mean element in the array.    

Given: arr = np.array([[1,2,np.nan],[4,2,6],[np.nan,np.nan,5]])    

In [29]:
# 6. 

arr = np.array([[1, 2, np.nan], [4, 2, 6], [np.nan, np.nan, 5]])

flat_arr = arr.flatten()
filtered_values = np.array([x for x in flat_arr if not np.isnan(x)])
mean_value = sum(filtered_values) / len(filtered_values)

result_array = np.where(np.isnan(arr), mean_value, arr)

print("Original Array:")
print(arr)
print("\nFilled Array:")
print(result_array)


Original Array:
[[ 1.  2. nan]
 [ 4.  2.  6.]
 [nan nan  5.]]

Filled Array:
[[1.         2.         3.33333333]
 [4.         2.         6.        ]
 [3.33333333 3.33333333 5.        ]]


Q7. Scenario: A sports team tracks player performance across 12 matches.    

Task: Create a (12, 5) array with random integers (0 to 100, representing     
scores). Mask the values where the player's score is less than the team's     
average score for that match. Replace these values with -1.     

Expected Output Example: Array with some values replaced by -1.     

In [35]:
# 7. 

scores = np.random.randint(0, 101, (12, 5))
match_avg = scores.mean(axis=1, keepdims=True)

masked_scores = np.where(scores < match_avg, -1, scores)
print("Masked Scores:\n", masked_scores)


(12, 5)

Q8. Scenario: A business tracks monthly revenue and expenses for 3    
departments across 6 months.    
    
Task: Create two (3, 6) random matrices for revenue and expenses. Perform    
element-wise multiplication and sum along the row axis to calculate the total    
profit for each department.    
    
Expected Output Example: A 1D array with the total profit per department.    

In [37]:
# 8.

revenue = np.random.randint(1000, 10001, (3, 6))
expenses = np.random.randint(100, 4000, (3, 6))

profit = np.sum(revenue - expenses, axis=1)
print("Total Profit for Each Department:", profit)


Total Profit for Each Department: [19816 29377 23086]


Q9. Scenario: A 5x5 matrix represents pixel intensity values in an image.    
    
Task: Rotate the matrix 90 degrees anti-clockwise without using loops or    
Python slicing.    
    
Expected Output Example: A rotated matrix    

In [41]:
# 9. 

matrix = np.random.randint(0, 10, (5, 5))
rotated_matrix = np.transpose(matrix)[::-1]

print("Original Matrix:\n", matrix)
print("Rotated Matrix:\n", rotated_matrix)

Original Matrix:
 [[6 6 4 9 0]
 [6 6 6 9 3]
 [9 3 4 2 6]
 [7 5 7 1 6]
 [8 0 0 3 6]]
Rotated Matrix:
 [[0 3 6 6 6]
 [9 9 2 1 3]
 [4 6 4 7 0]
 [6 6 3 5 0]
 [6 6 9 7 8]]


Q10. Scenario: A company tracks salaries of 15 employees in 3 departments.     
     
Task: Create a (3, 15) matrix of random salaries. Identify and print the     
department(s) where all employees have salaries above ₹50,000. Replace     
salaries less than ₹30,000 with the department's average salary.     
     
Expected Output Example: Original Salary matrix and Updated salary matrix.     

In [45]:
# 10.

salaries = np.random.randint(10000, 100000, (3, 15))
Original_salaries = salaries.copy()
high_salary_departments = np.all(salaries > 50000, axis=1)

for i in range(salaries.shape[0]):
    avg_salary = np.mean(salaries[i, salaries[i] > 30000])
    salaries[i, salaries[i] < 30000] = avg_salary

print("Original Salary Matrix:\n", Original_salaries)
print("Updated Salary Matrix:\n", salaries)

Original Salary Matrix:
 [[31728 37397 19157 64305 21603 85350 78354 92412 48866 83125 98067 60614
  78228 21424 64092]
 [34401 36910 32836 61787 54994 66564 37708 27099 90737 58108 34859 10524
  35161 17488 46474]
 [89527 32026 57449 49743 38556 53804 20648 34129 27342 98880 42883 76822
  24791 50865 35051]]
Updated Salary Matrix:
 [[31728 37397 68544 64305 68544 85350 78354 92412 48866 83125 98067 60614
  78228 68544 64092]
 [34401 36910 32836 61787 54994 66564 37708 49211 90737 58108 34859 49211
  35161 49211 46474]
 [89527 32026 57449 49743 38556 53804 54977 34129 54977 98880 42883 76822
  54977 50865 35051]]
